language: php

php:
    - 5.5

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - php composer.phar test

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover-coverage.xml

notifications:
  email:
    - m.orioli@apperclass.com
    - ruben.barilani.dev@gmail.com